<?php

namespace PMM\CoreBundle\Repository;

/**
 * ActeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeRepository extends \Doctrine\ORM\EntityRepository
{
}
