<?php

namespace PMM\CoreBundle\Repository;

/**
 * CommandeMedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeMedicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
