<?php

namespace PMM\CoreBundle\Repository;

/**
 * Medoc15Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Medoc15Repository extends \Doctrine\ORM\EntityRepository
{
}
