<?php

namespace PMM\CoreBundle\Repository;

/**
 * Medoc9Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Medoc9Repository extends \Doctrine\ORM\EntityRepository
{
}
