<?php

namespace PMM\CoreBundle\Repository;

/**
 * Medoc6Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Medoc6Repository extends \Doctrine\ORM\EntityRepository
{
}
