<?php

namespace PMM\CoreBundle\Repository;

/**
 * Medoc12Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Medoc12Repository extends \Doctrine\ORM\EntityRepository
{
}
