<?php

namespace PMM\CoreBundle\Repository;

/**
 * Medoc7Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Medoc7Repository extends \Doctrine\ORM\EntityRepository
{
}
