<?php

namespace PMM\LaboBundle\Repository;

/**
 * BulletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulletinRepository extends \Doctrine\ORM\EntityRepository{
    
    public function myFindOne($id){
        
        $qb = $this->createQueryBuilder('b');
        
        $qb
            ->where('b.id = :id')
            ->setParameter('id', $id);
        
        return $qb->getQuery()->getArrayResult();
    }
    
    public function myFindAll(){
        
        return $this->createQueryBuilder('b')->getQuery()->getArrayResult();
    }
}
