<?php

namespace PMM\LaboBundle\Repository;

/**
 * BulletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulletinRepository extends \Doctrine\ORM\EntityRepository
{
}
