<?php

namespace PMM\LaboBundle\Repository;

/**
 * Caisse1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Caisse2Repository extends \Doctrine\ORM\EntityRepository
{
}
