<?php

namespace PMM\LaboBundle\Repository;

/**
 * EcbuCuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcbuCuRepository extends \Doctrine\ORM\EntityRepository
{
}
