<?php

namespace PMM\LaboBundle\Repository;

/**
 * BiochimieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatBiochimieRepository extends \Doctrine\ORM\EntityRepository
{
}
