<?php

namespace PMM\LaboBundle\Repository;

/**
 * UrineLrcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatUrineLrcRepository extends \Doctrine\ORM\EntityRepository
{
}
