<?php

namespace PMM\LaboBundle\Repository;

/**
 * SerologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatSerologieRepository extends \Doctrine\ORM\EntityRepository
{
}
