<?php

namespace PMM\LaboBundle\Repository;

/**
 * FormuleLeucocytaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatFormuleLeucocytaireRepository extends \Doctrine\ORM\EntityRepository
{
}
