<?php

namespace PMM\LaboBundle\Repository;

/**
 * HematologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatHematologieRepository extends \Doctrine\ORM\EntityRepository
{
}
