<?php

namespace PMM\LaboBundle\Repository;

/**
 * PcvPuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatPcvPuRepository extends \Doctrine\ORM\EntityRepository
{
}
